# -*- coding: utf-8 -*-
"""Omars HW3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GRzDeWP-cgYeZwEYy5swKkrY2D7g3jtb

1. Printing, Data Types, and Input
"""

name = input("Enter your name: ")
age = input("Enter your age: ")

print(f"Hello, {name}. You are {age} years old.")

print(f"The data type of 'name' is {type(name)}")
print(f"The data type of 'age' is {type(age)}")

"""2. String Manipulations and Input

"""

hometown = input("Please enter the name of your hometown: ")

print("Hometown in Uppercase:", hometown.upper())

print("First three characters:", hometown[:3])

print("Hometown in Reverse:", hometown[::-1])

"""3. Numeric Operations and Input"""

import math

user_input = input("Enter a number: ")

try:
    number = float(user_input)

    result = number * number

    square_root = math.sqrt(result)

    print(f"The result of {number} squared is {result}")
    print(f"The square root of {result} is {square_root}")
except ValueError:
    print("Invalid input. Please enter a valid number.")

"""4. Boolean Evaluations

"""

print(10 > 5)
print(10 == 10)
print(8 != 9)

"""5. List Creation and Operations

"""

colors = ["red", "blue", "green"]

print("Original list:", colors)

print("First item:", colors[0])

colors[1] = "yellow"

print("Updated list:", colors)

colors[-1] = "purple"

print("Updated list with last item changed:", colors)

"""6. Indexing and Slicing

"""

numbers = [10, 20, 30, 40, 50]

print("Third item:", numbers[2])

print("First two numbers:", numbers[:2])

print("Last three numbers:", numbers[-3:])

"""7. Manipulating Elements

"""

animals = ['cat', 'dog', 'bird']

print("Initial list of animals:", animals)

animals.append('fish')

print("Updated list of animals:", animals)

"""8. Sorting


Print every second item from the sorted list.
"""

listr = [42, 8, 15, 23, 16]

print(listr)

listr.sort()

print(listr)

print("every second item from list:", listr[1::2])